package main

import (
	"fmt"
	"io"
	"log"
	"os"
)

const (
	disclaimer = `// Code generated by astits using internal/cmd/crc32_table. DO NOT EDIT`
	packet     = `package ts`
	filename   = `crc32_table.go`

	polynomial = 0x04c11db7
	tables     = 16
	perLine    = 8
)

func main() {
	file, err := os.Create(filename)
	if err != nil {
		log.Fatal(err)
	}
	defer func() { _ = file.Close() }()

	write(fmt.Fprintf(file, "%s\n%s\n\n", disclaimer, packet))
	generateTables(file, slicingTables())
}

// Table 0 is the byte-wise CRC table; table k is the CRC of a byte followed by k zero bytes.
func slicingTables() (t [tables][256]uint32) {
	for i := range uint32(256) {
		var k uint32
		for j := (i << 24) | 0x800000; j != 0x80000000; j <<= 1 {
			if (k^j)&0x80000000 != 0 {
				k = (k << 1) ^ polynomial
			} else {
				k <<= 1
			}
		}
		t[0][i] = k
	}
	for k := 1; k < tables; k++ {
		for i := range 256 {
			prev := t[k-1][i]
			t[k][i] = (prev << 8) ^ t[0][prev>>24]
		}
	}
	return
}

func generateTables(w io.Writer, t [tables][256]uint32) {
	write(fmt.Fprintf(w, "var tableCRC32 = [%d][256]uint32{", tables))
	for k := range t {
		write(fmt.Fprintf(w, "\n\t{"))
		for i, v := range t[k] {
			if i%perLine == 0 {
				write(fmt.Fprintf(w, "\n\t\t"))
			} else {
				write(fmt.Fprintf(w, " "))
			}
			write(fmt.Fprintf(w, "0x%08X,", v))
		}
		write(fmt.Fprintf(w, "\n\t},"))
	}
	write(fmt.Fprintf(w, "\n}\n"))
}

func write(_ int, err error) {
	if err != nil {
		log.Fatal(err)
	}
}
